site_name: Diaspora Service Documentation
site_url: https://github.com/haochenpan/diaspora-service
site_author: Haochen Pan
site_description: Documentation for Diaspora Service

repo_name: haochenpan/diaspora-service
repo_url: https://github.com/haochenpan/diaspora-service

copyright: Copyright &copy; 2023—Present Diaspora Team

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Ubuntu Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: static/octopus.svg
  logo: static/octopus.svg

plugins:
  - mkdocstrings

watch:
  - mkdocs.yml
  - README.md
  - docs/
  - action_provider/
  - common/
  - web_service/

extra:
  version:
    default: latest
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: foobar-author
      repo: foobar
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Development:
      - Introduction: index.md
      - Running: 1-running.md
      - Testing: 2-testing.md
      - Deployment: 3-deploying.md
      - Monitoring: 4-monitoring.md
      - Acknowledgments: acknowledgments.md
  - Action Provider:
      - Documentation: ap/api.md
      - Examples: ap/examples.md
  - Web Service:
      - Documentation: web/api.md
      - Examples: web/examples.md
  - Admin Console:
      - Introduction: console/intro.md
