name: Configure AWS Credentials

on:
  push:
    branches:
      - lightsail-deploy
  pull_request:
    branches:
      - lightsail-deploy

jobs:
  configure-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Verify AWS configuration
      run: |
        aws sts get-caller-identity
